name: 规则失效以及其他错误
description: 创建报告以帮助我们改进
body:
  - type: input
    attributes:
      label: 问题描述
      description: 简单清晰的说一下问题的描述.
    validations:
      required: true
  - type: input
    attributes:
      label: 从哪里开始出现这个问题
      description: |-
        例如
        ``某游戏的登陆页面``、
        ``内置的网页``、
        ``游戏房间内部``、
        ``商店页面`` 等
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截图
      description: 如果可以，请添加截图以帮助解释您的问题.
  - type: textarea
    attributes:
      label: 运行环境
      description: |-
        请说明当前的运行环境
        例如：
        ``操作系统``
        ``网络环境``(如 运营商等
