name: Update China IP list and generate BypassCN.rule

on:  
  workflow_dispatch:

  schedule: 
    - cron:  '0 2 */3 * *'

jobs:
  build:
    name: Generate BypassCN.rule
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into directory
      uses: actions/checkout@v3
    
    - name: Run the updategeoip-cn.sh
      run: ./tools/updategeoip-cn.sh
      shell: bash

    - name: Git Add BypassCNandLan.rules
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git fetch
        cp ./BypassCNandLan.rules ./rules/BypassCNandLan.rules
        git add ./rules/BypassCNandLan.rules
        git commit -am "Updated at $(date)" --allow-empty
            
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true
